'use client';

import { CSSProperties, PointerEvent as ReactPointerEvent, SyntheticEvent, useEffect, useReducer, useRef, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, Bookmark, Bot, Camera, ChevronRight, Clipboard, Download, ExternalLink, FileText, History, Home, Lock, Maximize2, Moon, PanelTop, Play, RefreshCw, RotateCcw, Search, Settings, Share2, ShieldCheck, Sparkles, Star, Sun, Trash2, UserRound, Wrench, X, ZoomIn, ZoomOut } from 'lucide-react';
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { useIsMobile } from '@/hooks/use-mobile';
import { activeTab, activity, cloneInitialState, loadState, LOCAL_DEMOS, makeId, PALETTES, resolvePalette, saveState, splitReducer, STORAGE_KEY, titleFromUrl, type Actor, type PaletteName, type PaneId, type SplitAction, type SplitState } from '@/lib/split-state';
import { normalizeNavigationInput } from '@/lib/validation';
import { createTools, registerTools } from '@/lib/webmcp';

type ToolView = 'notes' | 'watch' | 'bookmarks' | 'history' | 'settings' | 'compare' | 'activity';
type WebMcpStatus = { available: boolean; count: number; errors: string[] };
const WATCH_SERVICES = [{ name: 'Netflix', url: 'https://www.netflix.com' }, { name: 'Prime Video', url: 'https://www.primevideo.com' }, { name: 'Crunchyroll', url: 'https://www.crunchyroll.com' }, { name: 'YouTube', url: 'https://m.youtube.com' }];

function ActorBadge({ actor }: { actor: Actor }) {
  return actor === 'agent'
    ? <span className="inline-flex items-center gap-1 rounded-full bg-[#e7f4ff] px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-[#24658a]"><Bot className="size-3" /> Agent</span>
    : <span className="inline-flex items-center gap-1 rounded-full bg-[#eef2f6] px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-[#59687c]"><UserRound className="size-3" /> Human</span>;
}

function WebMcpHelp({ status, close }: { status: WebMcpStatus; close: () => void }) {
  const closeButton = useRef<HTMLButtonElement>(null);
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'failed'>('idle');
  useEffect(() => {
    closeButton.current?.focus();
    const handleKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [close]);
  const examplePrompt = "Use Split's site tools to tell me which workspace is currently active.";
  const copySplitUrl = async () => {
    try {
      const splitUrl = new URL(window.location.href); splitUrl.hash = ''; splitUrl.search = '';
      await navigator.clipboard.writeText(splitUrl.toString()); setCopyStatus('copied');
    } catch { setCopyStatus('failed'); }
  };
  return (
    <div role="presentation" className="fixed inset-0 z-50 flex items-end justify-center bg-[#172033]/35 p-3 sm:items-center" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}>
      <dialog open aria-modal="true" aria-labelledby="webmcp-help-title" className="relative m-0 max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-2xl border border-[var(--split-line)] bg-[var(--split-surface)] p-0 text-[var(--split-text)] shadow-[0_24px_80px_rgba(23,32,51,.3)]">
        <header className="flex items-start gap-3 border-b border-[var(--split-line)] bg-[var(--split-background)] p-4">
          <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--split-inactive)] text-[var(--split-primary)]">{status.available ? <Sparkles className="size-5" /> : <Bot className="size-5" />}</span>
          <div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-[0.15em] text-[var(--split-muted)]">Human + agent workspace</p><h2 id="webmcp-help-title" className="mt-0.5 text-base font-black">Use Split with an AI agent</h2></div>
          <button ref={closeButton} onClick={close} aria-label="Close WebMCP instructions" className="grid size-8 shrink-0 place-items-center rounded-lg text-[var(--split-muted)] hover:bg-[var(--split-inactive)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--split-primary)]"><X className="size-4" /></button>
        </header>
        <div className="space-y-4 p-4 text-xs leading-5">
          <div className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold ${status.available ? 'bg-[var(--split-inactive)] text-[var(--split-primary)]' : 'bg-[var(--split-background)] text-[var(--split-muted)]'}`}>{status.available ? <Sparkles className="size-3.5" /> : <ShieldCheck className="size-3.5" />}{status.available ? `WebMCP available · ${status.count} tools` : 'Human mode · WebMCP not detected'}</div>
          {status.available ? <>
            <p>This environment supports WebMCP. Split has registered {status.count} tools that an external compatible agent can discover and use.</p>
            <section className="rounded-xl border border-[var(--split-line)] bg-[var(--split-background)] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-[var(--split-muted)]">Example prompt</p><p className="mt-1 font-semibold">“{examplePrompt}”</p></section>
          </> : <>
            <p>Split works normally in Human mode. This browser or environment has not exposed WebMCP site tools to Split. In a compatible environment, Split exposes 11 tools that an external agent can discover and use.</p>
            <section className="rounded-xl border border-[var(--split-line)] bg-[var(--split-background)] p-3"><h3 className="font-bold">With ChatGPT</h3><ol className="mt-2 list-decimal space-y-1 pl-5"><li>Open the ChatGPT desktop app.</li><li>Start a Work or Codex chat.</li><li>Open ChatGPT&apos;s built-in browser.</li><li>Visit this Split URL in that browser.<div className="mt-2 flex flex-wrap items-center gap-2"><button type="button" onClick={() => void copySplitUrl()} className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--split-line)] bg-[var(--split-surface)] px-2.5 py-1.5 text-[10px] font-bold text-[var(--split-primary)] hover:bg-[var(--split-inactive)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--split-primary)]"><Clipboard className="size-3.5" /> Copy Split URL</button>{copyStatus !== 'idle' && <output aria-live="polite" className={`text-[10px] font-semibold ${copyStatus === 'copied' ? 'text-[var(--split-primary)]' : 'text-red-700'}`}>{copyStatus === 'copied' ? 'Copied!' : 'Clipboard unavailable—copy the address from your browser.'}</output>}</div></li><li>If site tools/WebMCP are available for your account and environment, ChatGPT can discover Split&apos;s tools automatically.</li><li>Ask: “{examplePrompt}”</li></ol></section>
            <section className="rounded-xl border border-[var(--split-line)] bg-[var(--split-background)] p-3"><h3 className="font-bold">Using Chrome?</h3><p className="mt-1 text-[var(--split-muted)]">Ordinary Chrome remains in Human mode unless the appropriate experimental WebMCP support is enabled. Chrome WebMCP testing requires the relevant experimental support or origin-trial configuration.</p></section>
          </>}
          <p className="text-[var(--split-muted)]">The agent is external to Split—no AI model is built in. No Split login, API key, or manual pairing is required.</p>
          <button onClick={close} className="w-full rounded-lg bg-[var(--split-primary)] px-3 py-2.5 text-sm font-bold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--split-primary)]">Got it</button>
        </div>
      </dialog>
    </div>
  );
}

function AppearanceSettings({ state, dispatch }: { state: SplitState; dispatch: (action: SplitAction) => void }) {
  const selectPalette = (paletteName: PaletteName) => dispatch({ type: 'set-appearance', paletteName, activity: activity('human', 'Changed Split palette', paletteName) });
  return <section className="mb-3 rounded-xl border border-[var(--split-line)] bg-[var(--split-surface)] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-wider text-[var(--split-muted)]">Original Split setting</p><h3 className="text-sm font-bold">Color palette</h3><p className="mt-1 text-[11px] leading-4 text-[var(--split-muted)]">Recolors the workspace, pane controls, T1–T4 tabs, divider, inputs, and quick tools.</p></div><button onClick={() => dispatch({ type: 'set-appearance', darkMode: !state.appearance.darkMode, activity: activity('human', state.appearance.darkMode ? 'Enabled light mode' : 'Enabled dark mode', state.appearance.paletteName) })} className="grid size-9 shrink-0 place-items-center rounded-lg bg-[var(--split-inactive)] text-[var(--split-primary)]" aria-label={state.appearance.darkMode ? 'Use light mode' : 'Use dark mode'}>{state.appearance.darkMode ? <Sun className="size-4" /> : <Moon className="size-4" />}</button></div><div className="mt-3 grid grid-cols-3 gap-2">{PALETTES.map((palette) => <button key={palette.name} onClick={() => selectPalette(palette.name)} aria-pressed={state.appearance.paletteName === palette.name} className={`flex items-center gap-2 rounded-lg border p-2 text-left text-[10px] font-bold ${state.appearance.paletteName === palette.name ? 'border-[var(--split-primary)] ring-2 ring-[var(--split-primary)]/20' : 'border-[var(--split-line)]'}`}><span className="size-4 rounded-full border border-black/10" style={{ backgroundColor: palette.primary }} />{palette.name}</button>)}</div><p className="mt-3 text-[10px] font-semibold text-[var(--split-muted)]">{state.appearance.darkMode ? 'Dark' : 'Light'} mode · selection persists in Split-owned state</p></section>;
}

interface BrowserPaneProps {
  paneId: PaneId;
  state: SplitState;
  dispatch: (action: SplitAction) => void;
  onBookmark: (paneId: PaneId) => void;
}

function BrowserPane({ paneId, state, dispatch, onBookmark }: BrowserPaneProps) {
  const tab = activeTab(state); const paneState = tab.panes[paneId];
  const [address, setAddress] = useState(paneState.url); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [reloadKey, setReloadKey] = useState(0);
  // oxlint-disable-next-line react/react-compiler -- synchronize the editable address with external pane navigation
  useEffect(() => { setAddress(paneState.url); }, [paneState.url]);
  const navigate = (event: SyntheticEvent<HTMLFormElement>) => {
    event.preventDefault(); setError('');
    try {
      const url = normalizeNavigationInput(address);
      dispatch({ type: 'navigate', tabId: tab.id, pane: paneId, url, title: titleFromUrl(url), activity: activity('human', 'Navigated browser pane', `${tab.label} ${paneId} → ${url}`) });
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Invalid address.'); }
  };
  const local = paneState.url in LOCAL_DEMOS;
  const blank = paneState.url === 'about:blank';
  const canBack = paneState.historyIndex > 0; const canForward = paneState.historyIndex < paneState.history.length - 1;
  const tell = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 1800); };
  const copyUrl = async () => { try { await navigator.clipboard.writeText(paneState.url); tell('Address copied'); } catch { tell('Clipboard unavailable'); } };
  const shareUrl = async () => { try { const canShare = typeof navigator.share === 'function'; if (canShare) await navigator.share({ title: paneState.title, url: new URL(paneState.url, window.location.href).href }); else await navigator.clipboard.writeText(new URL(paneState.url, window.location.href).href); tell(canShare ? 'Shared' : 'Address copied'); } catch (caught) { if ((caught as DOMException)?.name !== 'AbortError') tell('Share unavailable'); } };
  const downloadResource = () => { const anchor = document.createElement('a'); anchor.href = paneState.url; if (local) anchor.download = `${paneState.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase() || 'split-resource'}.html`; else { anchor.target = '_blank'; anchor.rel = 'noreferrer noopener'; } anchor.click(); tell(local ? 'Download started' : 'Opened browser-managed download'); };
  const goHome = () => dispatch({ type: 'navigate', tabId: tab.id, pane: paneId, url: paneState.homepage, title: titleFromUrl(paneState.homepage), activity: activity('human', 'Opened pane homepage', `${tab.label} ${paneId} → ${paneState.homepage}`) });
  const setScale = (textScale: number) => dispatch({ type: 'set-pane-preferences', tabId: tab.id, pane: paneId, textScale, activity: activity('human', 'Changed pane text size', `${tab.label} ${paneId} → ${Math.max(75, Math.min(150, textScale))}%`) });
  const scale = paneState.textScale / 100;
  return (
    <section onPointerDown={() => dispatch({ type: 'set-active-pane', pane: paneId })} className={`flex h-full min-h-[310px] flex-col overflow-hidden bg-[var(--split-surface)] ${state.activePane === paneId ? 'ring-2 ring-inset ring-[var(--split-primary)]' : ''}`} aria-label={`${paneId} browser pane`}>
      <div className="flex h-10 shrink-0 items-center gap-1 border-b border-[var(--split-line)] bg-[var(--split-background)] px-1.5">
        <span className="hidden min-w-8 text-center text-[9px] font-bold tracking-[0.12em] text-[var(--split-muted)] lg:block">{paneId === 'left' ? 'LEFT' : 'RIGHT'}</span>
        <button onClick={() => dispatch({ type: 'history-step', tabId: tab.id, pane: paneId, delta: -1 })} disabled={!canBack} aria-label={`Back in ${paneId} pane`} className="browser-control"><ArrowLeft /></button>
        <button onClick={() => dispatch({ type: 'history-step', tabId: tab.id, pane: paneId, delta: 1 })} disabled={!canForward} aria-label={`Forward in ${paneId} pane`} className="browser-control"><ArrowRight /></button>
        <button onClick={goHome} aria-label={`Open homepage in ${paneId} pane`} className="browser-control secondary"><Home /></button>
        <form onSubmit={navigate} className="flex min-w-0 flex-1 items-center rounded-md border border-[var(--split-line)] bg-[var(--split-surface)] focus-within:border-[var(--split-primary)] focus-within:ring-2">
          <Search className="ml-2 size-3.5 shrink-0 text-[var(--split-muted)]" />
          <input value={address} onChange={(event) => setAddress(event.target.value)} aria-label={`Search or enter URL for ${paneId} pane`} className="h-7 min-w-0 flex-1 bg-transparent px-2 text-xs text-[var(--split-text)] outline-none placeholder:text-[var(--split-muted)]" placeholder="Search or enter address" />
        </form>
        <button onClick={() => setReloadKey((value) => value + 1)} aria-label={`Refresh ${paneId} pane`} className="browser-control secondary"><RefreshCw /></button>
        <button onClick={() => onBookmark(paneId)} aria-label={`Bookmark ${paneId} pane`} className="browser-control secondary"><Star /></button>
      </div>
      {error && <div role="alert" className="border-b border-red-200 bg-red-50 px-3 py-1.5 text-[11px] text-red-700">{error}</div>}
      {notice && <output className="block border-b border-[var(--split-line)] bg-[var(--split-inactive)] px-3 py-1 text-[10px] font-semibold text-[var(--split-primary)]">{notice}</output>}
      <div className="relative min-h-0 flex-1 bg-white">
        <div className="absolute left-0 top-0 origin-top-left" style={{ width: `${100 / scale}%`, height: `${100 / scale}%`, transform: `scale(${scale})` }}>
          {local && <iframe key={`${paneState.url}-${reloadKey}`} src={paneState.url} title={`${paneState.title} in ${paneId} pane`} className="h-full w-full border-0" sandbox="allow-scripts allow-same-origin" />}
          {blank && <div className="grid h-full place-items-center bg-[#f8fafc] p-6 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl border border-[#c9d3df] bg-white text-[#14747c]"><PanelTop /></span><h2 className="mt-4 text-base font-semibold">New pane</h2><p className="mt-1 text-xs text-[#718095]">Enter an address above or ask a WebMCP agent to open a resource here.</p></div></div>}
          {!local && !blank && <div className="grid h-full place-items-center bg-[radial-gradient(circle_at_top_right,#e3f3f4,transparent_48%),#f8fafc] p-6"><article className="w-full max-w-md rounded-2xl border border-[#c9d3df] bg-white p-6 shadow-[0_18px_50px_rgba(23,32,51,.08)]"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#eef2f6] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-[#59687c]"><ShieldCheck className="size-3.5" /> Safe fallback</span><h2 className="mt-5 text-2xl font-bold tracking-tight">{paneState.title}</h2><p className="mt-2 break-all text-xs text-[#718095]">{paneState.url}</p><p className="mt-5 text-sm leading-6 text-[#59687c]">This website may prevent embedding through CSP or X-Frame-Options. Split preserves the pane and resource state without bypassing browser security.</p><a href={paneState.url} target="_blank" rel="noreferrer noopener" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#14747c] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#105f66]"><ExternalLink className="size-4" /> Open original page</a></article></div>}
        </div>
      </div>
      <div className="flex h-8 shrink-0 items-center gap-0.5 border-t border-[var(--split-line)] bg-[var(--split-background)] px-1.5 text-[9px] text-[var(--split-muted)]"><span className="mr-auto min-w-0 truncate">{paneState.title}</span><button onClick={() => setScale(paneState.textScale - 10)} className="browser-control secondary" aria-label={`Decrease ${paneId} text size`}><ZoomOut /></button><span className="w-7 text-center font-semibold">{paneState.textScale}%</span><button onClick={() => setScale(paneState.textScale + 10)} className="browser-control secondary" aria-label={`Increase ${paneId} text size`}><ZoomIn /></button><button onClick={copyUrl} className="browser-control secondary" aria-label={`Copy ${paneId} address`}><Clipboard /></button><button onClick={shareUrl} className="browser-control secondary" aria-label={`Share ${paneId} resource`}><Share2 /></button><button onClick={downloadResource} className="browser-control secondary" aria-label={`Download or open ${paneId} resource`}><Download /></button><span className="ml-0.5">{paneState.historyIndex + 1}/{paneState.history.length}</span></div>
    </section>
  );
}

function ToolPanel({ view, state, dispatch, close, onReset }: { view: ToolView; state: SplitState; dispatch: (action: SplitAction) => void; close: () => void; onReset: () => void }) {
  const [noteTitle, setNoteTitle] = useState(''); const [noteBody, setNoteBody] = useState(''); const [settingsError, setSettingsError] = useState('');
  const tab = activeTab(state); const comparison = state.comparisons[0];
  const submitNote = (event: SyntheticEvent<HTMLFormElement>) => { event.preventDefault(); const body = noteBody.trim(); if (!body) return; const createdAt = new Date().toISOString(); const title = noteTitle.trim() || 'Untitled'; dispatch({ type: 'add-note', note: { id: makeId('note'), title, body: body.slice(0, 2000), actor: 'human', createdAt }, activity: activity('human', 'Added note', title, createdAt) }); setNoteTitle(''); setNoteBody(''); };
  const createStarterComparison = () => {
    const left = tab.panes.left; const right = tab.panes.right; const createdAt = new Date().toISOString();
    dispatch({ type: 'add-comparison', comparison: { id: makeId('comparison'), title: `${left.title} ↔ ${right.title}`, summary: 'A lightweight comparison attached to the pages currently visible in Split.', leftUrl: left.url, rightUrl: right.url, actor: 'human', createdAt, rows: [{ dimension: 'Resource', left: left.title, right: right.title }, { dimension: 'Location', left: left.url, right: right.url }] }, activity: activity('human', 'Created comparison', `${left.title} and ${right.title}`, createdAt) });
  };
  const setHomepage = (event: SyntheticEvent<HTMLFormElement>, paneId: PaneId) => { event.preventDefault(); setSettingsError(''); try { const value = new FormData(event.currentTarget).get('homepage'); if (typeof value !== 'string') throw new Error('Invalid homepage.'); const homepage = normalizeNavigationInput(value); dispatch({ type: 'set-pane-preferences', tabId: tab.id, pane: paneId, homepage, activity: activity('human', 'Changed pane homepage', `${tab.label} ${paneId} → ${homepage}`) }); } catch (caught) { setSettingsError(caught instanceof Error ? caught.message : 'Invalid homepage.'); } };
  const openInPane = (paneId: PaneId, url: string, title: string) => dispatch({ type: 'navigate', tabId: tab.id, pane: paneId, url, title, activity: activity('human', `Opened ${title}`, `${tab.label} ${paneId} pane.`) });
  return (
    <aside className="fixed inset-y-3 right-3 z-40 flex w-[min(390px,calc(100vw-1.5rem))] flex-col overflow-hidden rounded-2xl border border-[var(--split-line)] bg-[var(--split-surface)] text-[var(--split-text)] shadow-[0_24px_80px_rgba(23,32,51,.24)]" aria-label="Split quick tools">
      <header className="flex h-13 items-center border-b border-[var(--split-line)] bg-[var(--split-background)] px-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.15em] text-[var(--split-muted)]">Quick tools</p><h2 className="text-sm font-bold capitalize">{view}</h2></div><button onClick={close} aria-label="Close quick tools" className="ml-auto grid size-8 place-items-center rounded-lg hover:bg-[var(--split-inactive)]"><X className="size-4" /></button></header>
      <div className="min-h-0 flex-1 overflow-y-auto p-4">
        {view === 'notes' && <><div className="mb-3 rounded-xl border border-[var(--split-line)] bg-[var(--split-background)] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--split-muted)]">Open notepad in workspace</p><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={() => openInPane('left', '/demo/notepad', 'Split Notepad')} className="rounded-lg bg-[var(--split-inactive)] px-3 py-2 text-xs font-bold">Left / top pane</button><button onClick={() => openInPane('right', '/demo/notepad', 'Split Notepad')} className="rounded-lg bg-[var(--split-inactive)] px-3 py-2 text-xs font-bold">Right / bottom pane</button></div></div><form onSubmit={submitNote} className="rounded-xl border border-[var(--split-line)] bg-[var(--split-background)] p-3"><input value={noteTitle} onChange={(event) => setNoteTitle(event.target.value)} maxLength={100} placeholder="Note title" className="h-9 w-full rounded-lg border border-[var(--split-line)] bg-[var(--split-surface)] px-3 text-sm outline-none focus:border-[var(--split-primary)]" /><textarea value={noteBody} onChange={(event) => setNoteBody(event.target.value)} maxLength={2000} placeholder="Write a note while both pages stay open…" className="mt-2 min-h-24 w-full resize-y rounded-lg border border-[var(--split-line)] bg-[var(--split-surface)] p-3 text-sm outline-none focus:border-[var(--split-primary)]" /><button className="mt-2 w-full rounded-lg bg-[var(--split-primary)] px-3 py-2 text-sm font-semibold text-white">Save note</button></form><div className="mt-3 space-y-2">{state.notes.map((note) => <article key={note.id} className="rounded-xl border border-[var(--split-line)] bg-[var(--split-surface)] p-3"><div className="flex items-center justify-between"><strong className="text-sm">{note.title}</strong><ActorBadge actor={note.actor} /></div><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-[var(--split-muted)]">{note.body}</p></article>)}</div></>}
        {view === 'watch' && <div className="space-y-2"><p className="mb-3 text-xs leading-5 text-[var(--split-muted)]">Choose a service and the Split pane where it should open.</p>{WATCH_SERVICES.map((service) => <article key={service.name} className="flex items-center gap-3 rounded-xl border border-[var(--split-line)] bg-[var(--split-surface)] p-3"><span className="grid size-9 place-items-center rounded-lg bg-[var(--split-inactive)] text-[var(--split-primary)]"><Play className="size-4" /></span><strong className="min-w-0 flex-1 text-sm">{service.name}</strong><button onClick={() => openInPane('left', service.url, service.name)} className="rounded-lg bg-[var(--split-inactive)] px-2.5 py-1.5 text-[10px] font-bold">Left</button><button onClick={() => openInPane('right', service.url, service.name)} className="rounded-lg bg-[var(--split-primary)] px-2.5 py-1.5 text-[10px] font-bold text-white">Right</button></article>)}</div>}
        {view === 'bookmarks' && <>{state.bookmarks.length === 0 ? <Empty icon={<Bookmark />} title="No bookmarks yet" body="Use the star in either browser bar or ask an agent to save a visible page." /> : <div className="space-y-2">{state.bookmarks.map((item) => <button key={item.id} onClick={() => dispatch({ type: 'navigate', tabId: state.activeTabId, pane: state.activePane, url: item.url, title: item.title, activity: activity('human', 'Opened bookmark', item.title) })} className="flex w-full items-center gap-3 rounded-xl border border-[#d9e0e8] bg-white p-3 text-left hover:border-[#14747c]"><Bookmark className="size-4 shrink-0 text-[#14747c]" /><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.title}</strong><span className="block truncate text-[10px] text-[#718095]">{item.url}</span></span><ActorBadge actor={item.actor} /><ChevronRight className="size-4 text-[#718095]" /></button>)}</div>}</>}
        {view === 'history' && <div className="space-y-4">{(['left', 'right'] as PaneId[]).map((paneId) => { const paneState = tab.panes[paneId]; return <section key={paneId} className="rounded-xl border border-[#d9e0e8] bg-white p-3"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wider text-[#718095]">{tab.label} {paneId} pane</p><h3 className="text-sm font-bold">Browsing history</h3></div><button onClick={() => dispatch({ type: 'clear-history', tabId: tab.id, pane: paneId, activity: activity('human', 'Cleared pane history', `${tab.label} ${paneId}; Split-owned history only.`) })} className="inline-flex items-center gap-1 rounded-lg px-2 py-1 text-[10px] font-semibold text-[#59687c] hover:bg-[#eef2f6]"><Trash2 className="size-3" /> Clear</button></div><div className="mt-2 space-y-1">{paneState.history.map((url, index) => <button key={`${url}-${index}`} onClick={() => dispatch({ type: 'history-jump', tabId: tab.id, pane: paneId, index })} className={`block w-full truncate rounded-lg px-2 py-1.5 text-left text-[11px] ${index === paneState.historyIndex ? 'bg-[#e9f5f6] font-semibold text-[#14747c]' : 'hover:bg-[#f4f7fb]'}`}>{url}</button>)}</div></section>; })}</div>}
        {view === 'settings' && <div className="space-y-3"><section className="rounded-xl border border-[#d9e0e8] bg-white p-3"><div className="flex items-start gap-3"><Lock className="mt-0.5 size-4 text-[#14747c]" /><div className="flex-1"><h3 className="text-sm font-bold">Private Split session</h3><p className="mt-1 text-[11px] leading-4 text-[#718095]">Stops this T workspace’s URLs and history from being written to Split local storage. It is not browser incognito and cannot hide traffic, cookies, downloads, or browser history.</p></div><button onClick={() => dispatch({ type: 'set-private-mode', tabId: tab.id, enabled: !tab.privateMode, activity: activity('human', tab.privateMode ? 'Ended private Split session' : 'Started private Split session', `${tab.label} persistence ${tab.privateMode ? 'restored' : 'suppressed'}.`) })} className={`rounded-lg px-3 py-2 text-xs font-bold ${tab.privateMode ? 'bg-[#172033] text-white' : 'bg-[#e9f5f6] text-[#14747c]'}`}>{tab.privateMode ? 'On' : 'Off'}</button></div></section>{(['left', 'right'] as PaneId[]).map((paneId) => <form key={paneId} onSubmit={(event) => setHomepage(event, paneId)} className="rounded-xl border border-[#d9e0e8] bg-white p-3"><label className="text-[9px] font-bold uppercase tracking-wider text-[#718095]">{paneId} pane homepage</label><div className="mt-2 flex gap-2"><input name="homepage" defaultValue={tab.panes[paneId].homepage} className="h-9 min-w-0 flex-1 rounded-lg border border-[#c9d3df] px-3 text-xs outline-none focus:border-[#14747c]" /><button className="rounded-lg bg-[#14747c] px-3 text-xs font-bold text-white">Save</button></div><button type="button" onClick={() => dispatch({ type: 'set-pane-preferences', tabId: tab.id, pane: paneId, homepage: tab.panes[paneId].url, activity: activity('human', 'Set current page as homepage', `${tab.label} ${paneId}`) })} className="mt-2 text-[10px] font-semibold text-[#14747c]">Use current page</button></form>)}{settingsError && <p role="alert" className="text-xs text-red-700">{settingsError}</p>}<section className="rounded-xl border border-amber-200 bg-amber-50 p-3"><h3 className="text-sm font-bold">Split-owned data</h3><p className="mt-1 text-[11px] leading-4 text-amber-900/70">Reset removes only this site’s workspaces, notes, bookmarks, preferences, and activity. It cannot clear the browser cache, cookies, or other sites’ data.</p><button onClick={onReset} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-amber-300 bg-white px-3 py-2 text-xs font-bold text-amber-900"><Trash2 className="size-3.5" /> Reset Split data</button></section><section className="rounded-xl border border-[#d9e0e8] bg-[#f8fafc] p-3"><h3 className="text-sm font-bold">Ad blocking</h3><p className="mt-1 text-[11px] leading-4 text-[#718095]">An ordinary website cannot intercept and block another site’s network requests like Android WebView or a browser extension. Split-WebMCP does not claim browser-level ad blocking.</p></section></div>}
        {view === 'settings' && <AppearanceSettings state={state} dispatch={dispatch} />}
        {view === 'compare' && <>{!comparison ? <Empty icon={<Sparkles />} title="Comparison is optional" body="Keep browsing in both panes. Create a small comparison only when it helps the current task." action={<button onClick={createStarterComparison} className="rounded-lg bg-[#14747c] px-3 py-2 text-xs font-semibold text-white">Compare visible pages</button>} /> : <article><ActorBadge actor={comparison.actor} /><h3 className="mt-3 text-lg font-bold">{comparison.title}</h3><p className="mt-1 text-xs leading-5 text-[#59687c]">{comparison.summary}</p><div className="mt-4 overflow-hidden rounded-xl border border-[#c9d3df]">{comparison.rows.map((row) => <div key={row.dimension} className="grid grid-cols-[.7fr_1fr_1fr] border-b border-[#d9e0e8] text-[11px] last:border-b-0"><strong className="bg-[#f4f7fb] p-2">{row.dimension}</strong><span className="border-l border-[#d9e0e8] p-2 text-[#59687c]">{row.left}</span><span className="border-l border-[#d9e0e8] p-2 text-[#59687c]">{row.right}</span></div>)}</div></article>}</>}
        {view === 'activity' && <div className="space-y-1">{state.activity.map((item) => <article key={item.id} className="flex gap-3 rounded-xl p-2.5 hover:bg-[#f4f7fb]"><span className={`grid size-8 shrink-0 place-items-center rounded-lg ${item.actor === 'agent' ? 'bg-[#e7f4ff] text-[#24658a]' : 'bg-[#eef2f6] text-[#59687c]'}`}>{item.actor === 'agent' ? <Bot className="size-4" /> : <UserRound className="size-4" />}</span><div><strong className="text-xs">{item.action}</strong><p className="mt-0.5 text-[11px] leading-4 text-[#718095]">{item.detail}</p></div></article>)}</div>}
      </div>
    </aside>
  );
}

function Empty({ icon, title, body, action }: { icon: React.ReactNode; title: string; body: string; action?: React.ReactNode }) {
  return <div className="grid min-h-72 place-items-center text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#e9f5f6] text-[#14747c]">{icon}</span><h3 className="mt-4 text-sm font-bold">{title}</h3><p className="mx-auto mt-2 max-w-xs text-xs leading-5 text-[#718095]">{body}</p>{action && <div className="mt-4">{action}</div>}</div></div>;
}

function QuickTools({ open, setOpen, view, setView, position, setPosition }: { open: boolean; setOpen: (value: boolean) => void; view: ToolView; setView: (value: ToolView) => void; position: { right: number; bottom: number }; setPosition: (value: { right: number; bottom: number }) => void }) {
  const drag = useRef<{ x: number; y: number; right: number; bottom: number; moved: boolean } | null>(null);
  const startDrag = (event: ReactPointerEvent<HTMLButtonElement>) => { drag.current = { x: event.clientX, y: event.clientY, right: position.right, bottom: position.bottom, moved: false }; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveDrag = (event: ReactPointerEvent<HTMLButtonElement>) => { if (!drag.current) return; const dx = event.clientX - drag.current.x; const dy = event.clientY - drag.current.y; if (Math.abs(dx) + Math.abs(dy) > 5) drag.current.moved = true; setPosition({ right: Math.max(8, Math.min(window.innerWidth - 58, drag.current.right - dx)), bottom: Math.max(34, Math.min(window.innerHeight - 66, drag.current.bottom - dy)) }); };
  const endDrag = () => { if (drag.current && !drag.current.moved) setOpen(!open); drag.current = null; };
  const items: Array<{ id: ToolView; icon: React.ReactNode; label: string }> = [{ id: 'notes', icon: <FileText />, label: 'Notes' }, { id: 'watch', icon: <Play />, label: 'Watch' }, { id: 'bookmarks', icon: <Bookmark />, label: 'Bookmarks' }, { id: 'history', icon: <History />, label: 'History' }, { id: 'settings', icon: <Settings />, label: 'Settings' }, { id: 'compare', icon: <Maximize2 />, label: 'Compare' }, { id: 'activity', icon: <Activity />, label: 'Activity' }];
  return <div className="fixed z-30 flex flex-col-reverse items-center gap-2" style={{ right: position.right, bottom: position.bottom }}>{open && items.map((item) => <button key={item.id} onClick={() => { setView(item.id); setOpen(true); }} title={item.label} aria-label={item.label} className={`grid size-10 place-items-center rounded-xl border shadow-lg ${view === item.id ? 'border-[var(--split-primary)] bg-[var(--split-inactive)] text-[var(--split-primary)]' : 'border-[var(--split-line)] bg-[var(--split-surface)] text-[var(--split-muted)]'}`}>{item.icon}</button>)}<button onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} aria-label="Drag or open quick tools" title="Drag or open quick tools" className="grid size-12 touch-none place-items-center rounded-2xl bg-[var(--split-primary)] text-white shadow-[0_10px_30px_rgba(20,116,124,.35)]"><Wrench className="size-5" /></button></div>;
}

export function SplitApp() {
  const [state, dispatch] = useReducer(splitReducer, undefined, cloneInitialState); const stateRef = useRef(state);
  const [hydrated, setHydrated] = useState(false); const [toolsOpen, setToolsOpen] = useState(false); const [toolView, setToolView] = useState<ToolView>('notes');
  const [status, setStatus] = useState<WebMcpStatus>({ available: false, count: 0, errors: [] }); const [webMcpHelpOpen, setWebMcpHelpOpen] = useState(false); const statusButton = useRef<HTMLButtonElement>(null); const mobile = useIsMobile();
  useEffect(() => { stateRef.current = state; }, [state]);
  // oxlint-disable-next-line react/react-compiler -- hydrate versioned browser storage after mount
  useEffect(() => { dispatch({ type: 'hydrate', state: loadState(window.localStorage) }); setHydrated(true); }, []);
  useEffect(() => { if (hydrated) saveState(window.localStorage, state); }, [state, hydrated]);
  useEffect(() => { let cancelled = false; let dispose = () => {}; const tools = createTools({ getState: () => stateRef.current, apply: (action) => dispatch(action) }); void registerTools(document.modelContext, tools).then((registration) => { if (cancelled) { registration.dispose(); return; } dispose = registration.dispose; setStatus({ available: registration.available, count: registration.registered.length, errors: registration.errors }); }); return () => { cancelled = true; dispose(); }; }, []);
  useEffect(() => { const receive = (event: MessageEvent) => { if (event.origin !== window.location.origin || !event.source) return; if (event.data?.type === 'split-notepad:request') { (event.source as Window).postMessage({ type: 'split-notepad:state', notes: stateRef.current.notes }, event.origin); return; } if (event.data?.type === 'split-notepad:add') { const body = typeof event.data.body === 'string' ? event.data.body.trim().slice(0, 2000) : ''; if (!body) return; const title = typeof event.data.title === 'string' ? event.data.title.trim().slice(0, 100) || 'Untitled' : 'Untitled'; const createdAt = new Date().toISOString(); dispatch({ type: 'add-note', note: { id: makeId('note'), title, body, actor: 'human', createdAt }, activity: activity('human', 'Added note from pane', title, createdAt) }); } }; window.addEventListener('message', receive); return () => window.removeEventListener('message', receive); }, []);
  const tab = activeTab(state);
  const palette = resolvePalette(state.appearance.paletteName, state.appearance.darkMode);
  const themeStyle = { '--split-primary': palette.primary, '--split-background': palette.background, '--split-text': palette.text, '--split-muted': palette.hint, '--split-line': palette.inputLine, '--split-inactive': palette.buttonInactive, '--split-handle': palette.handle, '--split-surface': state.appearance.darkMode ? '#1d2632' : '#ffffff' } as CSSProperties;
  const bookmarkPane = (paneId: PaneId) => { const current = tab.panes[paneId]; if (state.bookmarks.some((item) => item.url === current.url)) return; const createdAt = new Date().toISOString(); dispatch({ type: 'add-bookmark', bookmark: { id: makeId('bookmark'), title: current.title, url: current.url, actor: 'human', createdAt }, activity: activity('human', 'Saved bookmark', current.title, createdAt) }); };
  const closeWebMcpHelp = () => { setWebMcpHelpOpen(false); window.setTimeout(() => statusButton.current?.focus(), 0); };
  const reset = () => { window.localStorage.removeItem(STORAGE_KEY); dispatch({ type: 'hydrate', state: cloneInitialState() }); };
  const captureWorkspace = async () => { let stream: MediaStream | undefined; try { if (!navigator.mediaDevices?.getDisplayMedia) throw new Error('Screen capture is unavailable.'); stream = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: false }); const video = document.createElement('video'); video.srcObject = stream; await video.play(); await new Promise<void>((resolve) => window.setTimeout(resolve, 150)); const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png')); if (!blob) throw new Error('Capture failed.'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = `split-workspace-${new Date().toISOString().replace(/[:.]/g, '-')}.png`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(anchor.href), 1000); dispatch({ type: 'switch-tab', tabId: state.activeTabId, activity: activity('human', 'Captured workspace', 'Browser-authorized screen capture saved as PNG.') }); } catch (caught) { if ((caught as DOMException)?.name !== 'NotAllowedError') window.alert(caught instanceof Error ? caught.message : 'Screen capture unavailable.'); } finally { stream?.getTracks().forEach((track) => track.stop()); } };
  return (
    <main style={themeStyle} className="flex h-dvh min-h-[620px] flex-col overflow-hidden bg-[var(--split-background)] text-[var(--split-text)]">
      <header className="flex h-14 shrink-0 items-center border-b border-[var(--split-line)] bg-[var(--split-surface)] px-3 lg:px-4"><div className="grid size-9 place-items-center rounded-xl bg-[var(--split-primary)] text-sm font-black text-white">S</div><div className="ml-3"><h1 className="text-base font-black tracking-[0.15em]">SPLIT</h1><p className="text-[8px] font-bold uppercase tracking-[0.15em] text-[var(--split-muted)]">Dual Browser · WebMCP</p></div><div className="ml-auto flex items-center gap-1.5"><button onClick={() => void captureWorkspace()} title="Capture workspace with browser permission" aria-label="Capture workspace" className="grid size-8 place-items-center rounded-lg text-[var(--split-muted)] hover:bg-[var(--split-inactive)]"><Camera className="size-4" /></button><button ref={statusButton} onClick={() => setWebMcpHelpOpen(true)} aria-haspopup="dialog" aria-expanded={webMcpHelpOpen} className={`inline-flex h-8 max-w-[10rem] items-center gap-1.5 whitespace-nowrap rounded-full px-2.5 text-[10px] font-bold sm:max-w-none ${status.available ? 'bg-[var(--split-inactive)] text-[var(--split-primary)]' : 'bg-[var(--split-inactive)] text-[var(--split-muted)]'}`}>{status.available ? <Sparkles className="size-3.5 shrink-0" /> : <ShieldCheck className="size-3.5 shrink-0" />}<span className="truncate">{status.available ? `WebMCP available · ${status.count} tools` : 'Human mode · Try WebMCP'}</span></button><button onClick={reset} aria-label="Reset Split-owned data" title="Reset Split-owned data" className="grid size-8 place-items-center rounded-lg text-[var(--split-muted)] hover:bg-[var(--split-inactive)]"><RotateCcw className="size-4" /></button></div></header>
      <nav aria-label="Saved Split workspaces" className="grid h-12 shrink-0 grid-cols-4 gap-1.5 border-b border-[var(--split-line)] bg-[var(--split-background)] p-1.5 lg:px-3">{state.tabs.map((item) => <button key={item.id} onClick={() => dispatch({ type: 'switch-tab', tabId: item.id, activity: activity('human', 'Switched workspace', `${item.label} restored with both pane URLs and split ratio.`) })} className={`rounded-lg text-xs font-bold transition ${state.activeTabId === item.id ? 'bg-[var(--split-primary)] text-white shadow-sm' : 'bg-[var(--split-inactive)] text-[var(--split-text)]'}`}>{item.privateMode && <Lock className="mr-1 inline size-3" />}{item.label}<span className="ml-1 hidden text-[9px] font-medium opacity-65 sm:inline">{Math.round(item.splitRatio)}/{Math.round(100 - item.splitRatio)}</span></button>)}</nav>
      <section className="min-h-0 flex-1 p-1.5">
        <ResizablePanelGroup key={`${tab.id}-${mobile ? 'mobile' : 'desktop'}`} orientation={mobile ? 'vertical' : 'horizontal'} defaultLayout={{ left: tab.splitRatio, right: 100 - tab.splitRatio }} onLayoutChanged={(layout) => { if (typeof layout.left === 'number') dispatch({ type: 'set-split-ratio', tabId: tab.id, ratio: layout.left }); }}>
          <ResizablePanel id="left" minSize="20%"><BrowserPane paneId="left" state={state} dispatch={dispatch} onBookmark={bookmarkPane} /></ResizablePanel>
          <ResizableHandle withHandle className="mx-1 w-3 rounded-md bg-[var(--split-handle)] aria-[orientation=horizontal]:my-1 aria-[orientation=horizontal]:h-3 aria-[orientation=horizontal]:w-full" />
          <ResizablePanel id="right" minSize="20%"><BrowserPane paneId="right" state={state} dispatch={dispatch} onBookmark={bookmarkPane} /></ResizablePanel>
        </ResizablePanelGroup>
      </section>
      <footer className="flex min-h-7 shrink-0 items-center justify-between border-t border-[var(--split-line)] bg-[var(--split-primary)] px-3 py-1 text-[9px] text-white/75"><span className="flex items-center gap-1.5"><ShieldCheck className="size-3" /> Safe URLs · honest embed fallback · local workspace state</span><span className="hidden sm:block">Human + Agent share T1–T4, panes, notes, bookmarks, and evidence</span></footer>
      <QuickTools open={toolsOpen} setOpen={setToolsOpen} view={toolView} setView={setToolView} position={state.appearance.quickToolPosition} setPosition={(value) => dispatch({ type: 'set-quick-tool-position', ...value })} />
      {toolsOpen && <ToolPanel view={toolView} state={state} dispatch={dispatch} close={() => setToolsOpen(false)} onReset={reset} />}
      {webMcpHelpOpen && <WebMcpHelp status={status} close={closeWebMcpHelp} />}
    </main>
  );
}
