import { activeTab, activity, makeId, titleFromUrl, type Bookmark, type Comparison, type Note, type SplitAction, type SplitState } from './split-state.ts';
import { normalizeUrl, pane, record, rows, tab, text } from './validation.ts';

export interface ToolResult { content: Array<{ type: 'text'; text: string }>; structuredContent: Record<string, unknown> }
export interface WebMcpTool { name: string; title: string; description: string; inputSchema: Record<string, unknown>; annotations?: { readOnlyHint?: boolean; destructiveHint?: boolean; idempotentHint?: boolean }; execute: (input: unknown) => ToolResult | Promise<ToolResult> }
export interface ModelContextLike { registerTool: (tool: WebMcpTool, options?: { signal?: AbortSignal }) => void | Promise<void> }
declare global { interface Document { modelContext?: ModelContextLike } }

const empty = { type: 'object', properties: {}, additionalProperties: false } as const;
const output = (message: string, data: Record<string, unknown>): ToolResult => ({ content: [{ type: 'text', text: message }], structuredContent: data });
interface Dependencies { getState: () => SplitState; apply: (action: SplitAction) => void; now?: () => string }

export function createTools({ getState, apply, now = () => new Date().toISOString() }: Dependencies): WebMcpTool[] {
  return [
    { name: 'get_workspace', title: 'Get Split workspace', description: 'Read the complete current Split dual-browser workspace: active T1–T4 workspace, both browser panes, saved notes, bookmarks, comparisons, palette/dark-mode appearance, and recent human/agent activity. Use this first.', inputSchema: empty, annotations: { readOnlyHint: true }, execute: () => output('Current Split workspace.', { workspace: getState() }) },
    { name: 'get_panes', title: 'Get visible browser panes', description: 'Read the URLs, titles, and navigation positions currently visible in Split’s left/right or top/bottom browser panes.', inputSchema: empty, annotations: { readOnlyHint: true }, execute: () => { const state = getState(); const current = activeTab(state); return output(`Visible panes in ${current.label}.`, { tabId: current.id, orientation: 'responsive', panes: current.panes, splitRatio: current.splitRatio }); } },
    { name: 'get_tabs', title: 'Get saved Split workspaces', description: 'List Split’s T1–T4 saved workspaces. Each tab contains two independent browser pane states and a saved split ratio.', inputSchema: empty, annotations: { readOnlyHint: true }, execute: () => { const state = getState(); return output('Split saved workspaces.', { activeTabId: state.activeTabId, tabs: state.tabs }); } },
    { name: 'switch_workspace', title: 'Switch visible Split workspace', description: 'Switch the human-visible dual-browser workspace to T1, T2, T3, or T4. Both panes and the saved split ratio change together.', inputSchema: { type: 'object', additionalProperties: false, required: ['tabId'], properties: { tabId: { type: 'string', enum: ['tab1', 'tab2', 'tab3', 'tab4'] } } }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true }, execute: (input) => { const data = record(input); const state = getState(); const tabId = tab(data.tabId, state.activeTabId); const selected = state.tabs.find((item) => item.id === tabId)!; apply({ type: 'switch-tab', tabId, activity: activity('agent', 'Switched workspace', `${selected.label} restored with both panes.`, now()) }); return output(`Switched Split to ${selected.label}.`, { tabId, workspace: selected }); } },
    { name: 'open_resource', title: 'Open URL in a Split pane', description: 'Open a validated http/https URL or approved local demo page in a selected browser pane and optional T1–T4 workspace. This updates the exact pane visible to the human. External sites use an honest fallback card when browser embedding is not reliable.', inputSchema: { type: 'object', additionalProperties: false, required: ['url', 'pane'], properties: { url: { type: 'string', maxLength: 2048 }, pane: { type: 'string', enum: ['left', 'right'] }, tabId: { type: 'string', enum: ['tab1', 'tab2', 'tab3', 'tab4'] }, title: { type: 'string', maxLength: 120 } } }, annotations: { readOnlyHint: false, destructiveHint: false }, execute: (input) => { const data = record(input); const state = getState(); const url = normalizeUrl(data.url); const paneId = pane(data.pane); const tabId = tab(data.tabId, state.activeTabId); const title = text(data.title, 'title', 120, false) || titleFromUrl(url); apply({ type: 'navigate', tabId, pane: paneId, url, title, activity: activity('agent', 'Opened browser resource', `${title} in ${tabId.toUpperCase()} ${paneId} pane.`, now()) }); return output(`Opened ${title} in the ${paneId} pane.`, { tabId, pane: paneId, url, title }); } },
    { name: 'configure_pane', title: 'Configure Split pane', description: 'Adjust a pane’s web-safe text zoom and/or homepage in a selected T1–T4 workspace. These are visible, persistent Split workspace preferences; this does not alter browser-wide settings.', inputSchema: { type: 'object', additionalProperties: false, required: ['pane'], anyOf: [{ required: ['textScale'] }, { required: ['homepage'] }], properties: { pane: { type: 'string', enum: ['left', 'right'] }, tabId: { type: 'string', enum: ['tab1', 'tab2', 'tab3', 'tab4'] }, textScale: { type: 'number', minimum: 75, maximum: 150 }, homepage: { type: 'string', maxLength: 2048 } } }, annotations: { readOnlyHint: false, destructiveHint: false }, execute: (input) => { const data = record(input); const state = getState(); const paneId = pane(data.pane); const tabId = tab(data.tabId, state.activeTabId); if (data.textScale == null && data.homepage == null) throw new Error('Provide textScale or homepage.'); const textScale = data.textScale == null ? undefined : Number(data.textScale); if (textScale != null && (!Number.isFinite(textScale) || textScale < 75 || textScale > 150)) throw new Error('textScale must be between 75 and 150.'); const homepage = data.homepage == null ? undefined : normalizeUrl(data.homepage); apply({ type: 'set-pane-preferences', tabId, pane: paneId, textScale, homepage, activity: activity('agent', 'Configured browser pane', `${tabId.toUpperCase()} ${paneId}: ${textScale == null ? '' : `${textScale}% zoom `}${homepage == null ? '' : `home ${homepage}`}`.trim(), now()) }); return output(`Configured the ${paneId} pane.`, { tabId, pane: paneId, textScale, homepage }); } },
    { name: 'get_notes', title: 'Get Split notes', description: 'Read the shared Split notepad. Notes include human or agent provenance and timestamps.', inputSchema: empty, annotations: { readOnlyHint: true }, execute: () => output('Split notes.', { notes: getState().notes }) },
    { name: 'add_note', title: 'Add Split note', description: 'Add a titled note to Split’s shared notepad. The note appears immediately in the human quick-tools panel and is marked as an agent action.', inputSchema: { type: 'object', additionalProperties: false, required: ['body'], properties: { title: { type: 'string', maxLength: 100 }, body: { type: 'string', minLength: 1, maxLength: 2000 } } }, annotations: { readOnlyHint: false, destructiveHint: false }, execute: (input) => { const data = record(input); const body = text(data.body, 'body', 2000); const note: Note = { id: makeId('note'), title: text(data.title, 'title', 100, false) || 'Agent note', body, actor: 'agent', createdAt: now() }; apply({ type: 'add-note', note, activity: activity('agent', 'Added note', note.title, now()) }); return output('Added a note to Split.', { note }); } },
    { name: 'get_bookmarks', title: 'Get Split bookmarks', description: 'Read saved browser resources from Split’s shared bookmarks.', inputSchema: empty, annotations: { readOnlyHint: true }, execute: () => output('Split bookmarks.', { bookmarks: getState().bookmarks }) },
    { name: 'save_bookmark', title: 'Bookmark a browser resource', description: 'Save a validated URL to Split bookmarks. If url is omitted, saves the resource currently visible in the requested pane.', inputSchema: { type: 'object', additionalProperties: false, required: ['pane'], properties: { pane: { type: 'string', enum: ['left', 'right'] }, url: { type: 'string', maxLength: 2048 }, title: { type: 'string', maxLength: 120 } } }, annotations: { readOnlyHint: false, destructiveHint: false }, execute: (input) => { const data = record(input); const state = getState(); const paneId = pane(data.pane); const visible = activeTab(state).panes[paneId]; const url = data.url == null ? visible.url : normalizeUrl(data.url); const title = text(data.title, 'title', 120, false) || (data.url == null ? visible.title : titleFromUrl(url)); const existing = state.bookmarks.find((item) => item.url === url); if (existing) return output(`${title} is already bookmarked.`, { bookmark: existing, alreadySaved: true }); const bookmark: Bookmark = { id: makeId('bookmark'), title, url, actor: 'agent', createdAt: now() }; apply({ type: 'add-bookmark', bookmark, activity: activity('agent', 'Saved bookmark', title, now()) }); return output(`Bookmarked ${title}.`, { bookmark, alreadySaved: false }); } },
    { name: 'create_comparison', title: 'Compare visible browser resources', description: 'Create a structured comparison that supports—but does not replace—the dual-browser experience. The comparison is tied to the URLs currently visible in both panes and appears in Split’s quick-tools panel.', inputSchema: { type: 'object', additionalProperties: false, required: ['title', 'summary', 'rows'], properties: { title: { type: 'string', minLength: 1, maxLength: 120 }, summary: { type: 'string', minLength: 1, maxLength: 600 }, rows: { type: 'array', minItems: 1, maxItems: 12, items: { type: 'object', additionalProperties: false, required: ['dimension', 'left', 'right'], properties: { dimension: { type: 'string', maxLength: 80 }, left: { type: 'string', maxLength: 300 }, right: { type: 'string', maxLength: 300 }, verdict: { type: 'string', maxLength: 160 } } } } } }, annotations: { readOnlyHint: false, destructiveHint: false }, execute: (input) => { const data = record(input); const state = getState(); const current = activeTab(state); const comparison: Comparison = { id: makeId('comparison'), title: text(data.title, 'title', 120), summary: text(data.summary, 'summary', 600), leftUrl: current.panes.left.url, rightUrl: current.panes.right.url, rows: rows(data.rows), actor: 'agent', createdAt: now() }; apply({ type: 'add-comparison', comparison, activity: activity('agent', 'Created comparison', `${comparison.title} · ${comparison.rows.length} rows`, now()) }); return output(`Created ${comparison.title}.`, { comparison }); } },
  ];
}

export async function registerTools(context: ModelContextLike | undefined, tools: WebMcpTool[]) {
  if (!context || typeof context.registerTool !== 'function') return { available: false, registered: [] as string[], errors: [] as string[], dispose: () => {} };
  const controller = new AbortController(); const registered: string[] = []; const errors: string[] = [];
  for (const tool of tools) { try { await context.registerTool(tool, { signal: controller.signal }); registered.push(tool.name); } catch (error) { errors.push(`${tool.name}: ${error instanceof Error ? error.message : 'registration failed'}`); } }
  return { available: true, registered, errors, dispose: () => controller.abort() };
}
